global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'data-pipeline'
    static_configs:
      - targets: ['data-pipeline:8003']
    scrape_interval: 30s  # Increased from 15s to 30s
    scrape_timeout: 10s   # Added timeout
    metrics_path: '/metrics'
    scheme: 'http'
    
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s
